/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#ffb59d",
        "on-tertiary-fixed-variant": "#384b3b",
        "secondary-container": "#e6e3d3",
        "tertiary-container": "#8a9f8b",
        "surface-variant": "#e5e2e1",
        "tertiary-fixed-dim": "#b7ccb7",
        "on-secondary-fixed": "#1c1c13",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e5e2e1",
        "surface-container-high": "#eae7e7",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#e6e3d3",
        "primary": "#ab3500",
        "on-secondary-container": "#666558",
        "on-primary-fixed-variant": "#832600",
        "surface-tint": "#ab3500",
        "outline": "#8d7168",
        "secondary-fixed-dim": "#cac7b8",
        "surface-container": "#f0eded",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#48473c",
        "inverse-on-surface": "#f3f0ef",
        "tertiary": "#506352",
        "on-tertiary-fixed": "#0d1f12",
        "primary-fixed": "#ffdbd0",
        "surface": "#fcf9f8",
        "on-primary": "#ffffff",
        "background": "#fcf9f8",
        "surface-container-low": "#f6f3f2",
        "inverse-surface": "#313030",
        "on-surface": "#1c1b1b",
        "on-tertiary-container": "#243627",
        "primary-container": "#ff6b35",
        "on-surface-variant": "#594139",
        "surface-bright": "#fcf9f8",
        "tertiary-fixed": "#d2e8d2",
        "on-primary-fixed": "#390c00",
        "error": "#ba1a1a",
        "secondary": "#605f53",
        "surface-dim": "#dcd9d9",
        "outline-variant": "#e1bfb5",
        "on-primary-container": "#5f1900",
        "on-error-container": "#93000a",
        "on-background": "#1c1b1b",
        "inverse-primary": "#ffb59d",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "podium-gap": "8px",
        "margin-page": "24px",
        "stack-md": "16px",
        "gutter-row": "12px",
        "stack-sm": "4px",
        "stack-lg": "32px",
      },
      fontFamily: {
        "rank-number": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "label-caps": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "rank-number": ["24px", { lineHeight: "1", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "800" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "1.5", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "800" }],
        "body-sm": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
